name: "🐞 Bug Report"
description: Report a reproducible problem or error.
title: "[Bug]: "
labels: [bug]
body:
  - type: input
    id: plugin-version
    attributes:
      label: "Plugin Version"
      description: "Which version of the plugin are you using?"
      placeholder: "e.g. 1.2.3"
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: "Dependencies"
      description: |
        Please provide your dependency tree.
        For Gradle: `./gradlew dependencies`
        For Maven: `./mvnw dependency:tree`
      render: shell
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: "Description of the Problem"
      description: "What happened? What did you expect to happen instead?"
      placeholder: "Clear, detailed description of the issue."
    validations:
      required: true
